/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ComputerControl;
import exception.InputKosongException;
import exception.IdException;
import exception.DesktopKosongException;
import exception.NoCompSelectedException;
import exception.LaptopKosongException;
import javax.swing.JOptionPane;
import model.Computer;
/**
 *
 * @author Ravelino Sebastian
 */
public class ComputerView extends javax.swing.JFrame {
    private ComputerControl computerControl;
    private Computer c;
    String action = null;
    String d = "Desktop";
    String l = "Laptop";
    
    /**
     * Creates new form DosenView
     */
    public ComputerView() {
        initComponents();
        setDesktopComponent(false);
        setLaptopComponent(false);
        setComponent(false);
        setEditDeleteBtn(false);
        computerControl = new ComputerControl();
        showData();
    }
    
    public void setComponent(boolean value) {
        idInput.setEnabled(value);
        namaInput.setEnabled(value);
        processorInput.setEnabled(value);
        ramInput.setEnabled(value);
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }

    public void setDesktopComponent(boolean val) {
        desktopInput.setEnabled(val);
        jRadioButtonDesktop.setEnabled(val);
    }
    
    public void setLaptopComponent(boolean val) {
        laptopInput.setEnabled(val);
        jRadioButtonLaptop.setEnabled(val);
    }
    
    public void setEditDeleteBtn(boolean value) {
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }

    public void clearText() {
        idInput.setText("");
        namaInput.setText("");
        processorInput.setText("");
        ramInput.setText("");     
        desktopInput.setText("");
        laptopInput.setText("");
    }
    
    public void showData() {
        showDesktopTextArea.setText(computerControl.showDataComputerDesktop());
        showLaptopTextArea.setText(computerControl.showDataComputerLaptop());
    }
    
    public void inputKosongException() throws InputKosongException {
        if (idInput.getText().isEmpty() || namaInput.getText().isEmpty()
                || processorInput.getText().isEmpty()
                || ramInput.getText().isEmpty()) {
            throw new InputKosongException();
        }
    }
    
    public void desktopKosongException() throws DesktopKosongException {
        if(desktopInput.getText().isEmpty())
        {
            throw new DesktopKosongException();
        }
    }
    
    public void laptopKosongException() throws LaptopKosongException {
        if(laptopInput.getText().isEmpty())
        {
            throw new LaptopKosongException();
        }
    }
    
    public void idException() throws IdException {
        if (idInput.getText().length() > 8 && idInput.getText().length() < 5) {
            throw new IdException();
        }
    }
    
    public void noCompSelected() throws NoCompSelectedException {
        if (jRadioButtonDesktop.isSelected() == false && jRadioButtonLaptop.isSelected() == false)
        {
            throw new NoCompSelectedException();
        }
    }
    
    public String generateDesktopID()
    {
        String lastId = null;
        String tempId = null;
        String generatedId = null;
        int numberId;
        
        lastId = computerControl.getLastDesktopId();
        tempId = lastId.substring(4);
        numberId = Integer.parseInt(tempId) + 1;
        generatedId = "DES-" + String.valueOf(numberId);
        
        return generatedId;
    }
    
    public String generateLaptopID()
    {
        String lastId = null;
        String tempId = null;
        String generatedId = null;
        int numberId;
        
        lastId = computerControl.getLastLaptopId();
        tempId = lastId.substring(4);
        numberId = Integer.parseInt(tempId) + 1;
        generatedId = "LAP-" + String.valueOf(numberId);
        
        return generatedId;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupComputer = new javax.swing.ButtonGroup();
        sidebarPanel = new javax.swing.JPanel();
        computerPanel = new javax.swing.JPanel();
        npmLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        titleContent = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jRadioButtonDesktop = new javax.swing.JRadioButton();
        jRadioButtonLaptop = new javax.swing.JRadioButton();
        containerInputDesktop = new javax.swing.JPanel();
        desktopLabel = new javax.swing.JLabel();
        desktopInput = new javax.swing.JTextField();
        containerInputLaptop = new javax.swing.JPanel();
        laptopLabel = new javax.swing.JLabel();
        laptopInput = new javax.swing.JTextField();
        containerInputId = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        containerInputNama = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        containerInputProcessor = new javax.swing.JPanel();
        processorLabel = new javax.swing.JLabel();
        processorInput = new javax.swing.JTextField();
        containerInputRAM = new javax.swing.JPanel();
        ramLabel = new javax.swing.JLabel();
        ramInput = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        showDesktopPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDesktopTextArea = new javax.swing.JTextArea();
        showLaptopPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        showLaptopTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(204, 204, 255));

        computerPanel.setBackground(new java.awt.Color(204, 204, 255));
        computerPanel.setMaximumSize(new java.awt.Dimension(100, 90));
        computerPanel.setMinimumSize(new java.awt.Dimension(100, 90));

        npmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        npmLabel.setText("190710062");

        javax.swing.GroupLayout computerPanelLayout = new javax.swing.GroupLayout(computerPanel);
        computerPanel.setLayout(computerPanelLayout);
        computerPanelLayout.setHorizontalGroup(
            computerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(npmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        computerPanelLayout.setVerticalGroup(
            computerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computerPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(npmLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(computerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(computerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(424, 424, 424))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        containerPanel.setBackground(new java.awt.Color(204, 204, 255));

        titleContent.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleContent.setText("OBJECT PERSISTENCE 1");

        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        buttonGroupComputer.add(jRadioButtonDesktop);
        jRadioButtonDesktop.setText("Desktop");
        jRadioButtonDesktop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDesktopActionPerformed(evt);
            }
        });

        buttonGroupComputer.add(jRadioButtonLaptop);
        jRadioButtonLaptop.setText("Laptop");
        jRadioButtonLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLaptopActionPerformed(evt);
            }
        });

        containerInputDesktop.setBackground(new java.awt.Color(204, 204, 255));

        desktopLabel.setText("Daya Listrik");

        desktopInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desktopInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputDesktopLayout = new javax.swing.GroupLayout(containerInputDesktop);
        containerInputDesktop.setLayout(containerInputDesktopLayout);
        containerInputDesktopLayout.setHorizontalGroup(
            containerInputDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerInputDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktopInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerInputDesktopLayout.setVerticalGroup(
            containerInputDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputDesktopLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(containerInputDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desktopLabel)
                    .addComponent(desktopInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        containerInputLaptop.setBackground(new java.awt.Color(204, 204, 255));

        laptopLabel.setText("Baterai");

        laptopInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptopInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputLaptopLayout = new javax.swing.GroupLayout(containerInputLaptop);
        containerInputLaptop.setLayout(containerInputLaptopLayout);
        containerInputLaptopLayout.setHorizontalGroup(
            containerInputLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerInputLaptopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laptopLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(laptopInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        containerInputLaptopLayout.setVerticalGroup(
            containerInputLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputLaptopLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(containerInputLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laptopLabel)
                    .addComponent(laptopInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        containerInputId.setBackground(new java.awt.Color(204, 204, 255));

        idLabel.setText("ID Computer");

        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputIdLayout = new javax.swing.GroupLayout(containerInputId);
        containerInputId.setLayout(containerInputIdLayout);
        containerInputIdLayout.setHorizontalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        containerInputIdLayout.setVerticalGroup(
            containerInputIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        containerInputNama.setBackground(new java.awt.Color(204, 204, 255));

        namaLabel.setText("Nama Model");

        namaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputNamaLayout = new javax.swing.GroupLayout(containerInputNama);
        containerInputNama.setLayout(containerInputNamaLayout);
        containerInputNamaLayout.setHorizontalGroup(
            containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel)
                    .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerInputNamaLayout.setVerticalGroup(
            containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        containerInputProcessor.setBackground(new java.awt.Color(204, 204, 255));

        processorLabel.setText("Jenis Processor");

        processorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processorInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputProcessorLayout = new javax.swing.GroupLayout(containerInputProcessor);
        containerInputProcessor.setLayout(containerInputProcessorLayout);
        containerInputProcessorLayout.setHorizontalGroup(
            containerInputProcessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputProcessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputProcessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(processorLabel)
                    .addComponent(processorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        containerInputProcessorLayout.setVerticalGroup(
            containerInputProcessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputProcessorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(processorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        containerInputRAM.setBackground(new java.awt.Color(204, 204, 255));

        ramLabel.setText("Kapasitas RAM");

        ramInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerInputRAMLayout = new javax.swing.GroupLayout(containerInputRAM);
        containerInputRAM.setLayout(containerInputRAMLayout);
        containerInputRAMLayout.setHorizontalGroup(
            containerInputRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputRAMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ramLabel)
                    .addComponent(ramInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerInputRAMLayout.setVerticalGroup(
            containerInputRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputRAMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ramLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ramInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        showDesktopPanel.setBackground(new java.awt.Color(204, 204, 255));
        showDesktopPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desktop", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        showDesktopTextArea.setEditable(false);
        showDesktopTextArea.setColumns(20);
        showDesktopTextArea.setRows(5);
        jScrollPane1.setViewportView(showDesktopTextArea);

        javax.swing.GroupLayout showDesktopPanelLayout = new javax.swing.GroupLayout(showDesktopPanel);
        showDesktopPanel.setLayout(showDesktopPanelLayout);
        showDesktopPanelLayout.setHorizontalGroup(
            showDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDesktopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        showDesktopPanelLayout.setVerticalGroup(
            showDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDesktopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        showLaptopPanel.setBackground(new java.awt.Color(204, 204, 255));
        showLaptopPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laptop", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        showLaptopTextArea.setEditable(false);
        showLaptopTextArea.setColumns(20);
        showLaptopTextArea.setRows(5);
        jScrollPane3.setViewportView(showLaptopTextArea);

        javax.swing.GroupLayout showLaptopPanelLayout = new javax.swing.GroupLayout(showLaptopPanel);
        showLaptopPanel.setLayout(showLaptopPanelLayout);
        showLaptopPanelLayout.setHorizontalGroup(
            showLaptopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLaptopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        showLaptopPanelLayout.setVerticalGroup(
            showLaptopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLaptopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(showDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showLaptopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerPanelLayout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(12, 12, 12)
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBtn))
                            .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(containerInputProcessor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(containerInputNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(containerInputRAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(containerInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonLaptop)
                                    .addComponent(jRadioButtonDesktop)
                                    .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(containerInputDesktop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(containerInputLaptop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn)
                                .addGap(83, 83, 83))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn)
                .addGap(83, 83, 83))
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addComponent(titleContent, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleContent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(19, 19, 19)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(containerInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(containerInputProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerInputRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(jRadioButtonDesktop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerInputDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jRadioButtonLaptop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerInputLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addGap(18, 18, 18)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showLaptopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, 
                "Apakah yakin ingin menghapus data ?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if (getAnswer == JOptionPane.YES_OPTION ){
            try {
                if(action.equalsIgnoreCase("ubahDesktop") || action.equalsIgnoreCase("ubahLaptop")) {
                    computerControl.deleteDataComputer(idInput.getText());
                    JOptionPane.showMessageDialog(null, "Data Computer berhasil dihapus!");
                }
                clearText();
                buttonGroupComputer.clearSelection();
                action = null;
                showData();
            } catch (Exception e) {
                System.out.println("Error : " + e.getMessage());
            }
        }
        else{JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus!");}
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if(action.equalsIgnoreCase("ubahDesktop"))
        {
            setComponent(true);
            setDesktopComponent(true);
            idInput.setEnabled(false);
        }
        else if(action.equalsIgnoreCase("ubahLaptop"))
        {
            setComponent(true);
            setLaptopComponent(true);
            idInput.setEnabled(false);
        }
        else
        {
            setComponent(false);
            setDesktopComponent(false);
            setLaptopComponent(false);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        clearText();
        buttonGroupComputer.clearSelection();
        searchInput.setText("");
        setComponent(true);
        setDesktopComponent(true);
        setLaptopComponent(true);
        idInput.setEnabled(false);
        action = "Tambah";
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        clearText();
        setEditDeleteBtn(true);
        setComponent(false);
        setDesktopComponent(false);
        setLaptopComponent(false);
        buttonGroupComputer.clearSelection();

        try {
            c = computerControl.searchComputer(searchInput.getText());
            if(c == null)
            {
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Computer tidak ditemukan!", 
                        "Konfirmasi", JOptionPane.DEFAULT_OPTION); 
            }
            else if(c.getJenis().equalsIgnoreCase(d)) {
                action = "ubahDesktop";
                
                idInput.setText(c.getId());
                namaInput.setText(c.getNama());
                processorInput.setText(c.getProcessor());
                ramInput.setText(String.valueOf(c.getKapasitasRAM()));
                desktopInput.setText(String.valueOf(c.getDayaListrik()));
                jRadioButtonDesktop.setSelected(true);
            }
            else if(c.getJenis().equalsIgnoreCase(l)) {
                action = "ubahLaptop";
                
                idInput.setText(c.getId());
                namaInput.setText(c.getNama());
                processorInput.setText(c.getProcessor());
                ramInput.setText(String.valueOf(c.getKapasitasRAM()));
                laptopInput.setText(String.valueOf(c.getKapasitasBaterai()));
                jRadioButtonLaptop.setSelected(true);
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void processorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processorInputActionPerformed

    private void namaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaInputActionPerformed

    private void ramInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramInputActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            inputKosongException();
            idException();
            noCompSelected();
            
            if (action.equals("Tambah")) {
                if(jRadioButtonDesktop.isSelected() == true) {
                    try {
                        desktopKosongException();
                        c = new Computer(idInput.getText(),
                                namaInput.getText(),
                                processorInput.getText(), 
                                Integer.parseInt(ramInput.getText()), 
                                d,
                                Integer.parseInt(desktopInput.getText()),
                                0);
                        computerControl.insertDataComputer(c);
                        JOptionPane.showMessageDialog(this,
                            "Data Computer Desktop berhasil ditambah!");
                    } 
                    catch (DesktopKosongException e) 
                    {
                        JOptionPane.showMessageDialog(this, e.message());
                    }
                }
                else if(jRadioButtonLaptop.isSelected() == true) {
                    try {
                        laptopKosongException();
                        c = new Computer(idInput.getText(),
                                namaInput.getText(),
                                processorInput.getText(), 
                                Integer.parseInt(ramInput.getText()), 
                                l,
                                0,
                                Integer.parseInt(laptopInput.getText()));
                        computerControl.insertDataComputer(c);
                        JOptionPane.showMessageDialog(this,
                            "Data Laptop berhasil ditambah!");
                    }
                    catch (LaptopKosongException e) 
                    {
                        JOptionPane.showMessageDialog(this, e.message());
                    }
                }
            }
            else if(action.equals("ubahDesktop")) {
                c = new Computer(null,
                            namaInput.getText(),
                            processorInput.getText(), 
                            Integer.parseInt(ramInput.getText()), 
                            d,
                            Integer.parseInt(desktopInput.getText()),
                            0);
                    computerControl.updateDataComputer(c, searchInput.getText());
                    JOptionPane.showMessageDialog(this,
                        "Data Computer Desktop berhasil diedit!");
            }
            else if(action.equals("ubahLaptop")) {
                c = new Computer(null,
                            namaInput.getText(),
                            processorInput.getText(), 
                            Integer.parseInt(ramInput.getText()), 
                            d,
                            0,
                            Integer.parseInt(laptopInput.getText()));
                    computerControl.updateDataComputer(c, searchInput.getText());
                    JOptionPane.showMessageDialog(this,
                        "Data Computer Laptop berhasil diedit!");
            }
            clearText();
            showData();
            setComponent(false);
            setDesktopComponent(false);
            setLaptopComponent(false);
            setEditDeleteBtn(false);
            buttonGroupComputer.clearSelection();
            action = null;
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        } catch (IdException e) {
            JOptionPane.showMessageDialog(this, e.message());
        } catch (NoCompSelectedException e) {
            JOptionPane.showMessageDialog(this, e.message());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input RAM / Daya Listrik / Baterai bukan angka!");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setDesktopComponent(false);
        setLaptopComponent(false);
        buttonGroupComputer.clearSelection();
        setEditDeleteBtn(false);
        clearText();
        action = null;
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void jRadioButtonLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLaptopActionPerformed
        setDesktopComponent(false);
        idInput.setEnabled(false);
        idInput.setText(generateLaptopID());
    }//GEN-LAST:event_jRadioButtonLaptopActionPerformed

    private void jRadioButtonDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDesktopActionPerformed
        setLaptopComponent(false);
        idInput.setEnabled(false);
        idInput.setText(generateDesktopID());
    }//GEN-LAST:event_jRadioButtonDesktopActionPerformed

    private void desktopInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desktopInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desktopInputActionPerformed

    private void laptopInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptopInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laptopInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup buttonGroupComputer;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel computerPanel;
    private javax.swing.JPanel containerInputDesktop;
    private javax.swing.JPanel containerInputId;
    private javax.swing.JPanel containerInputLaptop;
    private javax.swing.JPanel containerInputNama;
    private javax.swing.JPanel containerInputProcessor;
    private javax.swing.JPanel containerInputRAM;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField desktopInput;
    private javax.swing.JLabel desktopLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JRadioButton jRadioButtonDesktop;
    private javax.swing.JRadioButton jRadioButtonLaptop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField laptopInput;
    private javax.swing.JLabel laptopLabel;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel npmLabel;
    private javax.swing.JTextField processorInput;
    private javax.swing.JLabel processorLabel;
    private javax.swing.JTextField ramInput;
    private javax.swing.JLabel ramLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel showDesktopPanel;
    private javax.swing.JTextArea showDesktopTextArea;
    private javax.swing.JPanel showLaptopPanel;
    private javax.swing.JTextArea showLaptopTextArea;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel titleContent;
    // End of variables declaration//GEN-END:variables
}
