/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Pembeli;
import model.Computer;
import model.Transaksi;
import control.ComputerControl;
import control.PembeliControl;
import control.TransaksiControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import table.TableTransaksi;
import exception.InputKosongException;

/**
 *
 * @author readybos
 */
public class TransaksiView extends javax.swing.JFrame {
    
    private TransaksiControl tc ;
    private ComputerControl cc ;
    private PembeliControl pc ;
    String action = null;
    List<Computer> listComputer;
    List<Pembeli> listPembeli;
    int selectedId = 0;
    
    /**
     * Creates new form TransaksiView
     */
    public TransaksiView() {
        initComponents();
        setComponent(false);
        tc = new TransaksiControl();
        cc = new ComputerControl();
        pc = new PembeliControl();
        setComputerToDropdown();
        setPembeliToDropdown();
        setEditDeleteBtn(false);
        showTransaksi();
    }
    
    public void setComputerToDropdown() {
        listComputer = cc.showListAllComputer();
        for (int i = 0; i < listComputer.size(); i++) {
            namaComputerDropdown.addItem(listComputer.get(i));
        }
    }
    
    public void setPembeliToDropdown() {
        listPembeli = pc.showListPembeli();
        for (int i = 0; i < listPembeli.size(); i++) {
            namaPembeliDropdown.addItem(listPembeli.get(i));
        }
    }
    
    // Method untuk mengeset komponen input dan button save, button cancel
    public void setComponent(boolean value) {
        namaComputerDropdown.setEnabled(value);
        namaPembeliDropdown.setEnabled(value);
        tanggalTransaksiInput.setEnabled(value);
        totalHargaInput.setEnabled(value);
        mouseCheckbox.setEnabled(value);
        mousepadCheckbox.setEnabled(value);
        tasCheckbox.setEnabled(value);

        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
     // Method untuk mengeset komponen button edit dan button delete
    public void setEditDeleteBtn(boolean value) {
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    // Method untuk mengeset value text dari komponen Input
    public void clearText() {
        tanggalTransaksiInput.setText("");
        totalHargaInput.setText("");
        namaComputerDropdown.setSelectedItem(ABORT);
        namaPembeliDropdown.setSelectedItem(ABORT);
        mouseCheckbox.setSelected(false);
        mousepadCheckbox.setSelected(false);
        tasCheckbox.setSelected(false);
        searchInput.setText("");
    }
    
    // Method untuk menampilkan data mata kuliah pada tabel
    public void showTransaksi() {
        tableTransaksi.setModel(tc.showTransaksi(""));
    }
    
    // Method untuk memeriksa input kosong
    public void inputKosongException() throws InputKosongException {
        if (tanggalTransaksiInput.getText().isEmpty() || totalHargaInput.getText().isEmpty()
                 || namaComputerDropdown.getSelectedIndex() == -1 || namaPembeliDropdown.getSelectedIndex() == -1) {
            throw new InputKosongException();
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        titleLabel2 = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        tempPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        computerPanel = new javax.swing.JPanel();
        computerIconLabel = new javax.swing.JLabel();
        defaultPanel = new javax.swing.JPanel();
        transaksiPanel = new javax.swing.JPanel();
        transaksiIconLabel = new javax.swing.JLabel();
        pembeliPanel = new javax.swing.JPanel();
        pembeliLabel = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        commandPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        formPanel = new javax.swing.JPanel();
        namaComputerLabel = new javax.swing.JLabel();
        namaComputerDropdown = new javax.swing.JComboBox<>();
        namaPembeliLabel = new javax.swing.JLabel();
        namaPembeliDropdown = new javax.swing.JComboBox<>();
        tanggalTransaksiLabel = new javax.swing.JLabel();
        tanggalTransaksiInput = new javax.swing.JTextField();
        totalHargaLabel = new javax.swing.JLabel();
        totalHargaInput = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        namaComputerLabel1 = new javax.swing.JLabel();
        mouseCheckbox = new javax.swing.JCheckBox();
        tasCheckbox = new javax.swing.JCheckBox();
        mousepadCheckbox = new javax.swing.JCheckBox();
        searchPanel = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        footerPanel = new javax.swing.JPanel();
        identitasPraktikan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setBackground(new java.awt.Color(0, 204, 204));
        titlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        titlePanel.setForeground(new java.awt.Color(255, 255, 255));

        titleLabel1.setFont(new java.awt.Font("Castellar", 1, 80)); // NOI18N
        titleLabel1.setText("U");

        titleLabel2.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        titleLabel2.setText("Gamer");

        titleLabel3.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        titleLabel3.setText("WORLD");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLabel1)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(titleLabel2)
                .addGap(0, 0, 0)
                .addComponent(titleLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tempPanel.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaksi");

        javax.swing.GroupLayout tempPanelLayout = new javax.swing.GroupLayout(tempPanel);
        tempPanel.setLayout(tempPanelLayout);
        tempPanelLayout.setHorizontalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tempPanelLayout.setVerticalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        computerPanel.setBackground(new java.awt.Color(11, 227, 166));
        computerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        computerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                computerPanelMouseClicked(evt);
            }
        });

        computerIconLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        computerIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/computer_resize.png"))); // NOI18N
        computerIconLabel.setText(" Computer");

        javax.swing.GroupLayout computerPanelLayout = new javax.swing.GroupLayout(computerPanel);
        computerPanel.setLayout(computerPanelLayout);
        computerPanelLayout.setHorizontalGroup(
            computerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(computerIconLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        computerPanelLayout.setVerticalGroup(
            computerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(computerIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        defaultPanel.setBackground(new java.awt.Color(11, 227, 166));

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        transaksiPanel.setBackground(new java.awt.Color(11, 227, 166));
        transaksiPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));

        transaksiIconLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        transaksiIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transaksiIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/trasaction.resize.png"))); // NOI18N
        transaksiIconLabel.setText(" Transaksi");

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiIconLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pembeliPanel.setBackground(new java.awt.Color(11, 227, 166));
        pembeliPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        pembeliPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembeliPanelMouseClicked(evt);
            }
        });

        pembeliLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        pembeliLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pembeliLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/pembeli.png"))); // NOI18N
        pembeliLabel.setText("Pembeli");

        javax.swing.GroupLayout pembeliPanelLayout = new javax.swing.GroupLayout(pembeliPanel);
        pembeliPanel.setLayout(pembeliPanelLayout);
        pembeliPanelLayout.setHorizontalGroup(
            pembeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pembeliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
        );
        pembeliPanelLayout.setVerticalGroup(
            pembeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pembeliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));

        commandPanel.setBackground(new java.awt.Color(255, 255, 255));
        commandPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Command", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        addBtn.setBackground(new java.awt.Color(11, 227, 166));
        addBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(204, 255, 51));
        editBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 153, 153));
        deleteBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 204, 255));
        saveBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 153, 153));
        cancelBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
        commandPanel.setLayout(commandPanelLayout);
        commandPanelLayout.setHorizontalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        commandPanelLayout.setVerticalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelBtn)
                .addGap(19, 19, 19))
        );

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        namaComputerLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaComputerLabel.setText("Nama Computer");

        namaPembeliLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPembeliLabel.setText("Nama Pembeli");

        tanggalTransaksiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tanggalTransaksiLabel.setText("Tanggal Transaksi");

        totalHargaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        totalHargaLabel.setText("Total Harga");

        namaComputerLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaComputerLabel1.setText("Bonus Pembelian");

        mouseCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        mouseCheckbox.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        mouseCheckbox.setText("Mouse");

        tasCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        tasCheckbox.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        tasCheckbox.setText("Tas");

        mousepadCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        mousepadCheckbox.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        mousepadCheckbox.setText("Mousepad");

        jLayeredPane1.setLayer(namaComputerLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mouseCheckbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(tasCheckbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(mousepadCheckbox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaComputerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mouseCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mousepadCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(namaComputerLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mouseCheckbox)
                .addGap(18, 18, 18)
                .addComponent(tasCheckbox)
                .addGap(18, 18, 18)
                .addComponent(mousepadCheckbox)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalHargaInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaComputerLabel)
                    .addComponent(namaPembeliLabel)
                    .addComponent(tanggalTransaksiLabel)
                    .addComponent(totalHargaLabel)
                    .addComponent(namaComputerDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaPembeliDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggalTransaksiInput))
                .addGap(39, 39, 39)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane1)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(namaComputerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaComputerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaPembeliLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPembeliDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggalTransaksiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalTransaksiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalHargaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalHargaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        searchBtn.setBackground(new java.awt.Color(51, 204, 255));
        searchBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(commandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(commandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        footerPanel.setBackground(new java.awt.Color(0, 204, 204));
        footerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));

        identitasPraktikan.setBackground(new java.awt.Color(0, 204, 204));
        identitasPraktikan.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        identitasPraktikan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        identitasPraktikan.setText("Nathanael Kevin Wijaya - 190710059 - PBO ABCD");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(identitasPraktikan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(identitasPraktikan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(pembeliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(defaultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defaultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(computerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pembeliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0)
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        
        clearText();
        searchInput.setText("");
        action = "Tambah";
        namaComputerDropdown.setSelectedIndex(0);
        namaPembeliDropdown.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        action = "Ubah";
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch (getAnswer) {
            case 0:
            //jika jawaban user adalah Yes
            try {
                tc.deleteTransaksi(selectedId);
                clearText();
                showTransaksi();
                setComponent(false);
                setEditDeleteBtn(false);

            } catch (Exception e) {
                System.out.println("Error : " + e.getMessage());
            }
            break;
            case 1:
            //jika jawaban user adalah No
            break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void computerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computerPanelMouseClicked
        // TODO add your handling code here:
        ComputerView cv = new ComputerView();
        this.dispose();
        cv.setVisible(true);
    }//GEN-LAST:event_computerPanelMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        setEditDeleteBtn(false);
        
        setComponent(false);

        try {
            TableTransaksi tt = tc.showTransaksi(searchInput.getText());
            if (tt.getRowCount() == 0) {
                //Ketika data yang dicari tidak ditemukan
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            } else {
                //Ketika data yang dicari ditemukan
                tableTransaksi.setModel(tt);
            }
            // Ketika button cari diklik maka kan menghapus seluruh isi input
            clearText();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String bonus = "";
        
        try {
            inputKosongException();
           // String kelas = "";
           // String durasi_iklan = null;
            int namaComputerIndex = namaComputerDropdown.getSelectedIndex();
            int namaPembeliIndex = namaPembeliDropdown.getSelectedIndex();
            Computer selectedComputer = listComputer.get(namaComputerIndex);
            Pembeli selectedPembeli = listPembeli.get(namaPembeliIndex);
            
            if (mouseCheckbox.isSelected()) {
                bonus = bonus + "Mouse";
            } 
            if (tasCheckbox.isSelected()) {
                bonus =  bonus + "Tas";
            } 
            if (mousepadCheckbox.isSelected()){
                bonus = bonus + "Mousepad";
            }
            
            if(bonus.equalsIgnoreCase("")){
                bonus = "-,-,-";
            }else if(bonus.equalsIgnoreCase("Mouse")){
                bonus = "Mouse,-,-";
            }else if(bonus.equalsIgnoreCase("Tas")){
                bonus = "-,Tas,-";
            }else if(bonus.equalsIgnoreCase("Mousepad")){
                bonus = "-,-,Mousepad";
            }else if(bonus.equalsIgnoreCase("MouseTas")){
                bonus = "Mouse,Tas,-";
            }else if(bonus.equalsIgnoreCase("TasMousepad")){
                bonus = "-,Tas,Mousepad";
            }else if(bonus.equalsIgnoreCase("MouseMousepad")){
                bonus = "Mouse,-,Mousepad";
            }else if(bonus.equalsIgnoreCase("MouseTasMousepad")){
                bonus = "Mouse,Tas,Mousepad";
            }
            
            if (action.equals("Tambah")) {
                //Ketika action berstatus tambah maka akan memanggil fungsi insert
                Transaksi t = new Transaksi(tanggalTransaksiInput.getText(), 
                        totalHargaInput.getText(), bonus, selectedComputer, selectedPembeli);
                tc.insertDataTransaksi(t);
            } else {
                //Ketika action berstatus ubah maka akan memanggil fungsi update
                Transaksi t = new Transaksi(selectedId, tanggalTransaksiInput.getText(), 
                        totalHargaInput.getText(), bonus, selectedComputer, selectedPembeli);
                tc.updateDataTransaksi(t);
            }
            clearText();
            showTransaksi();
            setComponent(false);

            setEditDeleteBtn(false);
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        // TODO add your handling code here:
        int indexComputer = -1;
        int indexPembeli = -1;
        setEditDeleteBtn(true);

        setComponent(false);

        int clickedRow = tableTransaksi.getSelectedRow();
        TableModel tableModel = tableTransaksi.getModel();

        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString());
        tanggalTransaksiInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        totalHargaInput.setText(tableModel.getValueAt(clickedRow, 4).toString());

        String id_computer = tableModel.getValueAt(clickedRow, 9).toString();
        for(Computer c : listComputer) {
            if (c.getId().equals(id_computer)) {
                indexComputer = listComputer.indexOf(c);
            }
        }
        namaComputerDropdown.setSelectedIndex(indexComputer);
        
        String temp = tableModel.getValueAt(clickedRow, 10).toString();
        Integer id_Pembeli = Integer.parseInt(temp);
        for(Pembeli p : listPembeli) {
            if (p.getId() == id_Pembeli) {
                indexPembeli = listPembeli.indexOf(p);
            }
        }
        namaPembeliDropdown.setSelectedIndex(indexPembeli);
        
        String bonus = tableModel.getValueAt(clickedRow, 5).toString();
        if(bonus.equalsIgnoreCase("-,-,-")){
            mouseCheckbox.setSelected(false);
            tasCheckbox.setSelected(false);
            mousepadCheckbox.setSelected(false);
        }else if(bonus.equalsIgnoreCase("Mouse,-,-")){
            mouseCheckbox.setSelected(true);
            tasCheckbox.setSelected(false);
            mousepadCheckbox.setSelected(false);
        }else if(bonus.equalsIgnoreCase("-,Tas,-")){
            mouseCheckbox.setSelected(false);
            tasCheckbox.setSelected(true);
            mousepadCheckbox.setSelected(false);
        }else if(bonus.equalsIgnoreCase("-,-,Mousepad")){
            mouseCheckbox.setSelected(false);
            tasCheckbox.setSelected(false);
            mousepadCheckbox.setSelected(true);
        }else if(bonus.equalsIgnoreCase("Mouse,Tas,-")){
            mouseCheckbox.setSelected(true);
            tasCheckbox.setSelected(true);
            mousepadCheckbox.setSelected(false);
        }else if(bonus.equalsIgnoreCase("-,Tas,Mousepad")){
            mouseCheckbox.setSelected(false);
            tasCheckbox.setSelected(true);
            mousepadCheckbox.setSelected(true);
        }else if(bonus.equalsIgnoreCase("Mouse,-,Mousepad")){
            mouseCheckbox.setSelected(true);
            tasCheckbox.setSelected(false);
            mousepadCheckbox.setSelected(true);
        }else if(bonus.equalsIgnoreCase("Mouse,Tas,Mousepad")){
            mouseCheckbox.setSelected(true);
            tasCheckbox.setSelected(true);
            mousepadCheckbox.setSelected(true);
        }
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void pembeliPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembeliPanelMouseClicked
        // TODO add your handling code here:
        PembeliView pv = new PembeliView();
        this.dispose();
        pv.setVisible(true);
    }//GEN-LAST:event_pembeliPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JLabel computerIconLabel;
    private javax.swing.JPanel computerPanel;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel identitasPraktikan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mouseCheckbox;
    private javax.swing.JCheckBox mousepadCheckbox;
    private javax.swing.JComboBox<Computer> namaComputerDropdown;
    private javax.swing.JLabel namaComputerLabel;
    private javax.swing.JLabel namaComputerLabel1;
    private javax.swing.JComboBox<Pembeli> namaPembeliDropdown;
    private javax.swing.JLabel namaPembeliLabel;
    private javax.swing.JLabel pembeliLabel;
    private javax.swing.JPanel pembeliPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField tanggalTransaksiInput;
    private javax.swing.JLabel tanggalTransaksiLabel;
    private javax.swing.JCheckBox tasCheckbox;
    private javax.swing.JPanel tempPanel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField totalHargaInput;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JLabel transaksiIconLabel;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
